name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  just_audio: ^0.10.4
  smooth_page_indicator: ^1.2.1
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  on_audio_query: ^2.9.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/logo.jpg
  - assets/audio/blinding_lights.mp3
  - assets/audio/stay.mp3
  - assets/audio/shape_of_you.mp3
  - assets/audio/levitating.mp3
  - assets/audio/peaches.mp3
  - assets/audio/bad_habits.mp3
  - assets/audio/senorita.mp3
  - assets/audio/believer.mp3